server:
  contextPath: /ccc
  port: 8080

spring:
  profiles:
#    active: postgres
    active: dev
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 25
    username: test
    password: test
  jpa:
    show-sql: true

security:
  basic:
    enabled: false
# demo only:
  user:
    password: password
    
logging:
  level: 
    org.springframework.security: INFO
    org.springframework.boot.actuate.audit.listener.AuditListener: DEBUG
