spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ccc
    username: ${pg.username}
    password: ${pg.password}
#postgres/<personal>
  database:
    driverClassName: org.postgresql.Driver